### PR TITLE
fix: conditional test logic

### PR DESCRIPTION
**Pull request by elecpower**

### CODE REVIEW

**Comment by elecpower** [comment]
wrong repo

**Comment by mpaperno** [comment]
I don't get the fix PR?  😢    diss...

Well thanks for pointing it out anyway!   😆

**Comment by elecpower** [comment]
Hi Max I didn't think you were maintaining. I'll reopen the PR with another bug fix so you can review and merge

**Comment by elecpower** [comment]
The EdgeTX project has forked your repo. Upgrading to Qt 5.15.2 and then to 6.6.
I'll create a PR to your repo when finished for you to consider.

**Comment by mpaperno** [comment]
Well, hasn't been much to maintain (that I know of). Though funnily enough, I was just making some changes to `ActionPushButton` because I found some possible issues while using it on another project.  Can't remember if I used that in Companion anywhere (though if I did and no one has mentioned any issues by now it's likely not a problem).

But by all means, I'm open to improvements and definitely fixes. Thanks!

Be careful with Qt6 migration.... IMHO. Not sure how well they're maintaining the desktop Widgets stuff these days, if at all. Their releases/features are now driven by corporate mandate, so...  Sad.  YMMV of course!

Cheers,
-Max

**Pull request closed without merging**
